In [1]:
import numpy as np

In [2]:
np.ndarray?

Init signature: np.ndarray(self, /, *args, **kwargs)
Docstring:     
ndarray(shape, dtype=float, buffer=None, offset=0,
        strides=None, order=None)

An array object represents a multidimensional, homogeneous array
of fixed-size items.  An associated data-type object describes the
format of each element in the array (its byte-order, how many bytes it
occupies in memory, whether it is an integer, a floating point number,
or something else, etc.)

Arrays should be constructed using `array`, `zeros` or `empty` (refer
to the See Also section below).  The parameters given here refer to
a low-level method (`ndarray(...)`) for instantiating an array.

For more information, refer to the `numpy` module and examine the
methods and attributes of an array.

Parameters
----------
(for the __new__ method; see Notes below)

shape : tuple of ints
    Shape of created array.
dtype : data-type, optional
    Any object that can be interpreted as a numpy data type.
buffer : object exposing buffer int

In [4]:
d0 = np.array([[1,2], [3,4]])

In [5]:
type(d0)

numpy.ndarray

In [7]:
d0@d0

array([[ 7, 10],
       [15, 22]])

In [8]:
x = np.array([1,2])
y = np.array([1.0, 2.0])
z = np.array([1,2], dtype=np.int64)

In [9]:
x

array([1, 2])

In [10]:
y

array([1., 2.])

In [11]:
z

array([1, 2], dtype=int64)

In [13]:
z.nbytes

16

In [17]:
np.copy?

Signature: np.copy(a, order='K')
Docstring:
Return an array copy of the given object.

Parameters
----------
a : array_like
    Input data.
order : {'C', 'F', 'A', 'K'}, optional
    Controls the memory layout of the copy. 'C' means C-order,
    'F' means F-order, 'A' means 'F' if `a` is Fortran contiguous,
    'C' otherwise. 'K' means match the layout of `a` as closely
    as possible. (Note that this function and :meth:`ndarray.copy` are very
    similar, but have different default values for their order=
    arguments.)

Returns
-------
arr : ndarray
    Array interpretation of `a`.

Notes
-----
This is equivalent to:

>>> np.array(a, copy=True)  #doctest: +SKIP

Examples
--------
Create an array x, with a reference y and a copy z:

>>> x = np.array([1, 2, 3])
>>> y = x
>>> z = np.copy(x)

Note that, when we modify x, y changes, but not z:

>>> x[0] = 10
>>> x[0] == y[0]
True
>>> x[0] == z[0]
False
File:      c:\users\administrator\anaconda3\lib\site-packages\numpy\lib\function_base

In [19]:
a = np.random.rand(3,3)
a

array([[0.80013077, 0.55241635, 0.80073904],
       [0.29584974, 0.95634027, 0.40056007],
       [0.57264778, 0.30712514, 0.27673952]])

In [20]:
b = np.copy(a)
b

array([[0.80013077, 0.55241635, 0.80073904],
       [0.29584974, 0.95634027, 0.40056007],
       [0.57264778, 0.30712514, 0.27673952]])

In [21]:
a == b

array([[ True,  True,  True],
       [ True,  True,  True],
       [ True,  True,  True]])

In [27]:
b[1][1] = 0
b

array([[0.80013077, 0.55241635, 0.80073904],
       [0.29584974, 0.        , 0.40056007],
       [0.57264778, 0.30712514, 0.27673952]])

In [28]:
a

array([[0.80013077, 0.55241635, 0.80073904],
       [0.29584974, 0.95634027, 0.40056007],
       [0.57264778, 0.30712514, 0.27673952]])

In [24]:
id(b)

1263852764016