In [1]:
import numpy as np

In [2]:
dir(np.random)

['Generator',
 'MT19937',
 'PCG64',
 'Philox',
 'RandomState',
 'SFC64',
 'SeedSequence',
 '__RandomState_ctor',
 '__all__',
 '__builtins__',
 '__cached__',
 '__doc__',
 '__file__',
 '__loader__',
 '__name__',
 '__package__',
 '__path__',
 '__spec__',
 'absolute_import',
 'beta',
 'binomial',
 'bit_generator',
 'bounded_integers',
 'bytes',
 'chisquare',
 'choice',
 'common',
 'default_rng',
 'dirichlet',
 'division',
 'entropy',
 'exponential',
 'f',
 'gamma',
 'generator',
 'geometric',
 'get_state',
 'gumbel',
 'hypergeometric',
 'laplace',
 'logistic',
 'lognormal',
 'logseries',
 'mt19937',
 'mtrand',
 'multinomial',
 'multivariate_normal',
 'negative_binomial',
 'noncentral_chisquare',
 'noncentral_f',
 'normal',
 'pareto',
 'pcg64',
 'permutation',
 'philox',
 'poisson',
 'power',
 'print_function',
 'rand',
 'randint',
 'randn',
 'random',
 'random_integers',
 'random_sample',
 'ranf',
 'rayleigh',
 'sample',
 'seed',
 'set_state',
 'sfc64',
 'shuffle',
 'standard_cauchy',
 'st

In [10]:
# Random values in a given shape.random samples from a uniform distribution over ``[0, 1)``.
# 均匀分布
print(np.random.rand())
print(np.random.rand(2))
print(np.random.rand(2,2))

0.385492637039051
[0.86353805 0.85951537]
[[0.17277398 0.39026816]
 [0.12914539 0.70930347]]
0.5095486546218752


In [5]:
# Return a sample (or samples) from the "standard normal" distribution. filled 
# with random floats sampled from a univariate "normal" (Gaussian)
# 高斯/正态分布
print(np.random.randn())
print(np.random.randn(4))
print(np.random.randn(2,2))

-0.9568556527616838
[ 0.78202295 -1.18679834  0.10388984  0.09046281]
[[ 0.78748091  0.50608481]
 [-1.01765791 -1.09549079]]


# KMean新闻分类